-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS prototipo.categorias
(
    id_categoria serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_categoria_padre integer,
    CONSTRAINT categorias_pkey PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS prototipo.disponibilidad_usuarios
(
    id_disponibilidad serial NOT NULL,
    id_usuario integer NOT NULL,
    fecha date NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT disponibilidad_usuarios_pkey PRIMARY KEY (id_disponibilidad)
);

CREATE TABLE IF NOT EXISTS prototipo.eventos
(
    id_evento serial NOT NULL,
    id_usuario_propietario integer NOT NULL,
    id_categoria integer NOT NULL,
    titulo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone NOT NULL,
    id_ubicacion integer,
    CONSTRAINT eventos_pkey PRIMARY KEY (id_evento)
);

CREATE TABLE IF NOT EXISTS prototipo.log_accesos
(
    id_log serial NOT NULL,
    id_usuario integer,
    fecha_acceso timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT log_accesos_pkey PRIMARY KEY (id_log)
);

CREATE TABLE IF NOT EXISTS prototipo.participaciones
(
    id_evento integer NOT NULL,
    id_invitado integer NOT NULL,
    rol character varying(50) COLLATE pg_catalog."default",
    estado_confirmacion character varying(20) COLLATE pg_catalog."default" DEFAULT 'pendiente'::character varying,
    CONSTRAINT participaciones_pkey PRIMARY KEY (id_evento, id_invitado)
);

CREATE TABLE IF NOT EXISTS prototipo.tareas
(
    id_tarea serial NOT NULL,
    id_evento integer NOT NULL,
    id_responsable integer NOT NULL,
    titulo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(150) COLLATE pg_catalog."default" NOT NULL,
    prioridad character varying(20) COLLATE pg_catalog."default" DEFAULT 'Media'::character varying,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'Pendiente'::character varying,
    fecha_limite timestamp without time zone NOT NULL,
    CONSTRAINT tareas_pkey PRIMARY KEY (id_tarea)
);

CREATE TABLE IF NOT EXISTS prototipo.ubicaciones
(
    id_ubicacion serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(200) COLLATE pg_catalog."default",
    ciudad character varying(100) COLLATE pg_catalog."default" NOT NULL,
    capacidad integer,
    CONSTRAINT ubicaciones_pkey PRIMARY KEY (id_ubicacion)
);

CREATE TABLE IF NOT EXISTS prototipo.usuario_emails
(
    id_usuario integer NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_emails_pkey PRIMARY KEY (id_usuario, email)
);

CREATE TABLE IF NOT EXISTS prototipo.usuario_telefonos
(
    id_usuario integer NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_telefonos_pkey PRIMARY KEY (id_usuario, telefono)
);

CREATE TABLE IF NOT EXISTS prototipo.usuarios
(
    id_usuario serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fecha_registro date NOT NULL DEFAULT CURRENT_DATE,
    activo boolean DEFAULT true,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS prototipo.categorias
    ADD CONSTRAINT categorias_id_categoria_padre_fkey FOREIGN KEY (id_categoria_padre)
    REFERENCES prototipo.categorias (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS prototipo.disponibilidad_usuarios
    ADD CONSTRAINT disponibilidad_usuarios_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES prototipo.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS prototipo.eventos
    ADD CONSTRAINT eventos_id_categoria_fkey FOREIGN KEY (id_categoria)
    REFERENCES prototipo.categorias (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS prototipo.eventos
    ADD CONSTRAINT eventos_id_ubicacion_fkey FOREIGN KEY (id_ubicacion)
    REFERENCES prototipo.ubicaciones (id_ubicacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS prototipo.eventos
    ADD CONSTRAINT eventos_id_usuario_propietario_fkey FOREIGN KEY (id_usuario_propietario)
    REFERENCES prototipo.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS prototipo.log_accesos
    ADD CONSTRAINT log_accesos_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES prototipo.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS prototipo.participaciones
    ADD CONSTRAINT participaciones_id_evento_fkey FOREIGN KEY (id_evento)
    REFERENCES prototipo.eventos (id_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS prototipo.participaciones
    ADD CONSTRAINT participaciones_id_invitado_fkey FOREIGN KEY (id_invitado)
    REFERENCES prototipo.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS prototipo.tareas
    ADD CONSTRAINT tareas_id_evento_fkey FOREIGN KEY (id_evento)
    REFERENCES prototipo.eventos (id_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS prototipo.tareas
    ADD CONSTRAINT tareas_id_responsable_fkey FOREIGN KEY (id_responsable)
    REFERENCES prototipo.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS prototipo.usuario_emails
    ADD CONSTRAINT usuario_emails_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES prototipo.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS prototipo.usuario_telefonos
    ADD CONSTRAINT usuario_telefonos_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES prototipo.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
